server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.local
  persistentVolume:
    enabled: true
    storageClass: "local-path"
    accessModes:
      - ReadWriteOnce
    size: 10Gi
