ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - grafana.local
  path: /
persistence:
  enabled: true
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  size: 5Gi
